language: python
python:
  - "3.6"

service:
  - docker

stages:
  - build
  - test

before_script:
  - cp fromilyserver/settings.example fromilyserver/settings.py

jobs:
  include:
    - stage: build
      script:
        - make build
        - make migrations
    - stage: test
      script:
        - make test
