language: python
service:
  - docker

stages:
  - build
  - test

jobs:
  include:
    - stage: build
      script:
        - cp fromilyserver/settings.example fromilyserver/settings.py
        - make build
        - make migrations
    - stage: test
      script: make test
