# Generated by Django 2.2 on 2019-04-10 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordServer',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('server_str', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DiscordUser',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('user_str', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserServerData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userdata', to='fromily.DiscordServer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serverdata', to='fromily.DiscordUser')),
            ],
            options={
                'unique_together': {('user', 'server')},
            },
        ),
        migrations.CreateModel(
            name='DPointRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('reason', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
                ('userserverdata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dpoints', to='fromily.UserServerData')),
            ],
        ),
        migrations.AddField(
            model_name='discordserver',
            name='dictator',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fromily.DiscordUser'),
        ),
    ]
