# Generated by Django 2.2 on 2019-04-07 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordServer',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('server_str', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DiscordUser',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('user_str', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserServerData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dpoints', models.IntegerField(default=0)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fromily.DiscordServer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fromily.DiscordUser')),
            ],
            options={
                'unique_together': {('user', 'server')},
            },
        ),
        migrations.AddField(
            model_name='discorduser',
            name='servers',
            field=models.ManyToManyField(through='fromily.UserServerData', to='fromily.DiscordServer'),
        ),
        migrations.AddField(
            model_name='discordserver',
            name='dictator',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fromily.DiscordUser'),
        ),
        migrations.AddField(
            model_name='discordserver',
            name='users',
            field=models.ManyToManyField(related_name='_discordserver_users_+', through='fromily.UserServerData', to='fromily.DiscordUser'),
        ),
    ]
