# Generated by Django 2.2 on 2019-04-07 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fromily', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discordserver',
            name='users',
        ),
        migrations.RemoveField(
            model_name='discorduser',
            name='servers',
        ),
        migrations.AlterField(
            model_name='discordserver',
            name='dictator',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fromily.DiscordUser'),
        ),
    ]
