# Generated by Django 2.2 on 2019-04-10 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fromily', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discordserver',
            old_name='server_str',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='discorduser',
            old_name='user_str',
            new_name='name',
        ),
    ]
