# Generated by Django 2.2 on 2019-04-15 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fromily', '0002_auto_20190410_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dpointrecord',
            name='reason',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
