# Generated by Django 2.2 on 2019-04-15 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fromily', '0003_auto_20190415_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discordserver',
            name='dictator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fromily.DiscordUser'),
        ),
    ]
