# Generated by Django 2.2 on 2019-04-08 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fromily', '0003_auto_20190407_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userserverdata',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userdata', to='fromily.DiscordServer'),
        ),
        migrations.AlterField(
            model_name='userserverdata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serverdata', to='fromily.DiscordUser'),
        ),
    ]
