# Generated by Django 2.2 on 2019-04-15 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fromily', '0004_auto_20190415_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discordserver',
            name='dictator',
        ),
        migrations.AddField(
            model_name='discordserver',
            name='dictator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fromily.DiscordUser'),
        ),
    ]
